import = [
    "~/.config/alacritty/themes/themes/zenburn.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
decorations = "Buttonless"
startup_mode = "Maximized"


